### ISSUE TITLE
Change default or add option to not display 'Applying Plugin org.jetbrains.kotlin.* to *' in console

### ISSUE THREAD

**Issue by devPalacio** [handstandsam/kmp4free#11]
The current default adds a lot of noise to the logs, it would be nice to be able to turn it off.

**Comment by handstandsam** [comment]
Thanks, fixed here: https://github.com/handstandsam/kmp4free/commit/af5a0ecd13cb69194aef5f896e9f19e2c5d8c531

**Comment by handstandsam** [comment]
Will be included in `0.1.1` which should be released shortly.
