### ISSUE TITLE
Unable to resolve plugin

### ISSUE THREAD

**Issue by ThanosFisherman** [handstandsam/kmp4free#7]
Hi,

I can't seem to be able to resolve this plugin. I've included the custom maven repo as shown in the readme but I get is the following exception when adding the plugin itself to the plugins {} block.

```
* Exception is:
java.lang.NoClassDefFoundError: org/gradle/configurationcache/extensions/CharSequenceExtensionsKt
	at com.handstandsam.kmp4free.internal.Kmp4FreeSourceSetMagic.extendConfigurationsAndSourceSets(Kmp4FreeSourceSetMagic.kt:65)
	at com.handstandsam.kmp4free.internal.Kmp4FreeMagic.enableKotlinJvm(Kmp4FreeMagic.kt:48)
	at com.handstandsam.kmp4free.Kmp4FreePlugin.apply(Kmp4FreePlugin.kt:25)
```

**Comment by ThanosFisherman** [comment]
I also tried that on a different project and now I get the following error:

```
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'com.handstandsam.kmp4free', version: '0.1.0-SNAPSHOT'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.handstandsam.kmp4free:com.handstandsam.kmp4free.gradle.plugin:0.1.0-SNAPSHOT')
```

**Comment by handstandsam** [comment]
Sorry for the late reply!
---
Ahh, yes, you need to use the snapshot repo until this officially published on maven central.  I plan on publishing to maven central in early/mid-july after is use `kmp4free` in a larger codebase to ensure it's working as expected.

Instructions: https://github.com/handstandsam/kmp4free#plugin-installation

Add the following maven repo to use the snapshot versions:
```
pluginManagement {
    repositories {
        // ...
        maven { url = "https://s01.oss.sonatype.org/content/repositories/snapshots/" }
    }
}
```

**Comment by ThanosFisherman** [comment]
Hi,

I still get the same error even though I added the custom maven repo 

```kotlin
repositories {
    mavenCentral()
    maven { setUrl("https://s01.oss.sonatype.org/content/repositories/snapshots/") }
}
```

```kotlin
plugins {
    id("com.handstandsam.kmp4free") version "0.1.0-SNAPSHOT"
}
```
Am I missing something?

**Comment by handstandsam** [comment]
You may have to put it in the `pluginManagement ` block which is separate from the normal `repositories` block.  I'm hoping to release a non-snapshot version soon, but I'm waiting on validating it on a larger project before I do.

Thanks for your patience, but hopefully that works.  You can see usage of the snapshot in `ShoppingApp` here: https://github.com/handstandsam/ShoppingApp/blob/main/settings.gradle
